maps/aim_dojo_csz.res
maps/aim_dojo_csz.txt
gfx/env/dojo1up.tga
gfx/env/dojo1dn.tga
gfx/env/dojo1lf.tga
gfx/env/dojo1rt.tga
gfx/env/dojo1ft.tga
gfx/env/dojo1bk.tga
models/dojo1/arbre5.mdl
models/dojo1/arbre.mdl
models/dojo1/dojo_swords.mdl
models/dojo1/katana_stand.mdl
models/dojo1/rock2.mdl
models/dojo1/rock3.mdl
models/dojo1/rock4.mdl
sprites/dojo1/branche.spr
sprites/dojo1/feuillage.spr
sprites/dojo1/feuillage1.spr
sprites/dojo1/herbe.spr
models/dojo1/by_boat_metal.mdl
models/dojo1/meeuw.mdl
sound/dojo1/ocean.wav
models/dojo1/seagull.mdl
sound/dojo1/gadget1.wav
